"""Initial tables and index

Revision ID: c4f6ee51d53a
Revises: cacfe0e51f25
Create Date: 2025-06-27 18:29:48.244657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f6ee51d53a'
down_revision: Union[str, Sequence[str], None] = 'cacfe0e51f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'published_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'published_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
